(setf FRM-1
      '(MTRANS (AGENT (HUMAN (GENDER (FEMALE))
                             (F-NAME (V NAME1))
                             (L-NAME (GRENTZ))))))
(setf FRM-2
      '(MTRANS (AGENT (HUMAN (F-NAME (SALLY))
                             (GENDER (V GEND1))
                             (L-NAME (GRENTZ))))
               (RECIP (HUMAN (GENDER (MALE))
                             (REL (SON (F-NAME (FREDDY))
                                       (OF (HUMAN (GENDER (FEMALE))
                                                  (F-NAME (SALLY))
                                                  (L-NAME (GRENTZ))))))
                             (AGE (TEEN))
                             (L-NAME (V L-NAME2))))))

(setf FRM-3
      '(MTRANS (AGENT (HUMAN (F-NAME (SALLY))
                             (GENDER (V GEND1))
                             (L-NAME (GRENTZ))))
               (RECIP (HUMAN (GENDER (MALE))
                             (REL (SON (F-NAME (FREDDY))
                                       (OF (HUMAN (GENDER (FEMALE))
                                                  (F-NAME (SALLY))
                                                  (L-NAME (GRENTZ))))))))))

(setf FRM-4
      '(MTRANS (AGENT (HUMAN (GENDER (FEMALE))
                             (F-NAME (SALLY))
                             (L-NAME (V L-NAME1))))
               (RECIP (HUMAN (GENDER (MALE))
                             (REL (SON (OF (V OF-1))))))))

(setf FR-L1
      '((MTRANS (AGENT (V X1))
                (RECIP (V Y1))
                (OBJECT (V OBJ1)))
        (BELIEVE (AGENT (V Y1))
                 (OBJECT (IS-LIAR (AGENT (V X1)))))))

(setf FR-L2
      '((BELIEVE (AGENT (HUMAN (F-NAME (SALLY))
                               (GENDER (FEMALE))))
                 (OBJECT (IS-LIAR (AGENT (HUMAN (F-NAME (HANK))
                                                (GENDER (MALE)))))))
        (STEALS (AGENT (HUMAN (F-NAME (HANK))
                              (GENDER (MALE))))
                (OBJECT (VEHICLE)))
        (MTRANS (AGENT (HUMAN (F-NAME (HANK))
                              (GENDER (MALE))))
                (OBJECT (BUY (AGENT (HUMAN (F-NAME (HANK))
                                           (GENDER (MALE))))
                             (OBJECT (DONUTS))
                             (TIME (FUTURE))))
                (RECIP (HUMAN (F-NAME (SALLY))
                              (GENDER (FEMALE)))))))

(setf FR-L3
      '((BELIEVE (AGENT (HUMAN (F-NAME (SALLY))
                               (GENDER (FEMALE))))
                 (OBJECT (IS-LIAR (AGENT (HUMAN (F-NAME (HANK))
                                                (GENDER (MALE)))))))
        (STEALS (AGENT (HUMAN (F-NAME (HANK))
                              (GENDER (MALE))))
                (OBJECT (VEHICLE)))
        (MTRANS (AGENT (HUMAN (F-NAME (FREDDY))
                              (GENDER (MALE))))
                (OBJECT (BUY (AGENT (HUMAN (F-NAME (FREDDY))
                                           (GENDER (MALE))))
                             (OBJECT (DONUTS))
                             (TIME (FUTURE))))
                (RECIP (HUMAN (F-NAME (SALLY))
                              (GENDER (FEMALE)))))))

(load "hw3.lsp")
